b151210067/b151210067/Controllers/AccessoriesController.cs
using b151210067.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class AccessoriesController : Controller
    {
        // GET: Accessory
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult Index()
        {
            var model = context.Accessories;
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (context != null)
            {
                context.Dispose();
            }
        }
    }
}

b151210067/b151210067/Controllers/ProductsController.cs
using b151210067.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class ProductsController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult Index(string category)
        {
            var model = context.Products.Where(p => p.Category.Name == category);
            ViewBag.Category = category;
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (context != null)
            {
                context.Dispose();
            }
        }
    }
}

b151210067/b151210067/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ÇOCUK DÜNYASI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ÇOCUK DÜNYASI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div id="test"class="navbar-collapse collapse">
                <ul class="nav navbar-nav test">
                    <li>@Html.ActionLink("ANASAYFA", "Index", "Home")</li>
                    <li>@Html.ActionLink("KIZ ÇOCUK", "Index", "Products", new { category = "FemaleChild" }, null)</li>
                    <li>@Html.ActionLink("ERKEK ÇOCUK", "Index", "Products", new { category = "MaleChild"}, null)</li>
                    <li>@Html.ActionLink("AKSESUAR", "Index", "Accessories")</li>
                    <li>@Html.ActionLink("MAĞAZALARIMIZ", "Magazalarımız", "Home")</li>
                    <li>@Html.ActionLink("MÜŞTERİ HİZMETLERİ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("DİL SEÇENEĞİ", "Dilsecenegi", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Çocuk Dünyası</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>