b151210067/b151210067/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
              return View();
        }
        public ActionResult Kızcocuk()
        {
            ViewBag.Message = "Kız çocuk sayfasındasınız.";

            return View();
        }
        public ActionResult Erkekcocuk()
        {
            ViewBag.Message = "Erkek çocuk sayfasındasınız.";

            return View();
        }
        public ActionResult Aksesuar()
        {
            ViewBag.Message = "Aksesuar sayfasındasınız.";

            return View();
        }
        public ActionResult Magazalarımız()
        {
            ViewBag.Message = "Mağazalarımız sayfasındasınız.";

            return View();
        }
    }
}

b151210067/b151210067/Controllers/MessagesController.cs
using b151210067.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class MessagesController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        [HttpPost]
        public ActionResult NewMessage(string Body, string SenderName, string SenderEmail, string SenderUserName, string PhoneNumber)
        {
            if (ModelState.IsValid)
            {
                context.Messages.Add(new Message { Body = Body, SenderEmail = SenderEmail, SenderName = SenderName, PhoneNumber=PhoneNumber, SenderUserName = SenderUserName });
                context.SaveChanges();
            }
            return RedirectToAction("Contact", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (context != null)
            {
                context.Dispose();
            }
        }
    }
}

b151210067/b151210067/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

b151210067/b151210067/Views/Home/Aksesuar.cshtml
@{
    ViewBag.Title = "Aksesuar";
}

<h2>Aksesuar</h2>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">            
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a1.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">89,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Sırt Çantası</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a2.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">150,00 TL</font></h4>
                            <h4><font face="Buxton Sketch">Sırt Çantası</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a3.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">69,99 TL</font></h4>
                            <h4><font face="Buxton Sketch">Sırt Çantası</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a4.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">10,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Saç Bandı</font></h4>
                            <h4><font face="Buxton Sketch">Atkı 14,99 TL</font></h4>
                            <h4><font face="Buxton Sketch">Çanta 25,00 TL</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a5.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">35,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Taç</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a6.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">15,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Saç Bandı</font></h4>
                            <h4><font face="Buxton Sketch">Bileklik 3,00 TL</font></h4>
                            <h4><font face="Buxton Sketch">Kolye 5,00 TL </font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a7.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">19,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Bere</font></h4>
                            <h4><font face="Buxton Sketch">Gözlük 25,00 TL</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a8.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">29,90 TL</font></h4>
                            <h4><font face="Buxton Sketch">Atkı</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/a9.jpeg" />
                        <div class="caption">
                            <h4 class="pull-right"><font face="Buxton Sketch">27,00 TL</font></h4>
                            <h4><font face="Buxton Sketch">Şapka</font></h4>
                            <h4><font face="Buxton Sketch">Papyon 6,00 TL</font></h4>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

b151210067/b151210067/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Müşteri Hizmetleri";
}

<h3>@ViewBag.Message</h3>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row carousel-holder">
                <div class="col-md-6">
                    <img src="~/Images/musterihizmetleriarkaplan.jpeg" />
                </div>
                <div class="col-md-6">
                    <form action="@Url.Action("NewMessage","Messages")" method="post">
                        <div class="contact-form">
                            <center>
                                <h2><font face="Buxton Sketch">İletişim Formu</font></h2>
                            </center>
                            <hr style="border-color:#cae1ff">
                            <div class="form-group">
                                <font face="Buxton Sketch">
                                    <label class="col-sm-4 control-label">Adınız:</label>
                                    <input id="ad" type="text" name="SenderName" class="form-control">
                                </font>
                            </div>
                            <div class="form-group">
                                <font face="Buxton Sketch">
                                    <label class="col-sm-4 control-label" font face="Buxton Sketch">Soyadınız:</label>
                                    <input id="soyad" type="text" name="SenderUserName" class="form-control">
                                </font>
                            </div>
                            <div class="form-group">
                                <font face="Buxton Sketch">
                                    <label class="col-sm-4 control-label">E-Posta:</label>
                                    <input id="eposta" type="text" name="SenderEmail" class="form-control">
                                </font>
                            </div>
                            <div class="form-group">
                                <font face="Buxton Sketch">
                                    <label class="col-sm-4 control-label">GSM:</label>
                                    <input id="gsm" type="text" name="PhoneNumber" class="form-control">
                                </font>
                            </div>
                            <div class="form-group">
                                <font face="Buxton Sketch">
                                    <label class="col-sm-4 control-label">Mesajınız:</label>
                                    @Html.TextArea("Body", null, new { @class = "form-control", placeholder = "Mesajınız...", rows = 6, columns = 40 })
                                </font>
                            </div>
                            <div class="form-group">
                                <center>
                                    <font face="Buxton Sketch">
                                        <button type="submit" class="col-sm-push-7 btn btn-primary">Gönder</button>
                                    </font>
                                </center>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

b151210067/b151210067/Views/Home/Erkekcocuk.cshtml
@{
    ViewBag.Title = "Erkekcocuk";
}

<h2>Erkekcocuk</h2>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row carousel-holder">
                <div class="col-md-12">
                    <img src="~/Images/erkekcocuksayfasi.jpeg" />
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e1.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">159,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Mont</font></h4>
                                <p>
                                    Pantolon 50,00 TL
                                    <br>Kazak 35,99 TL
                                    <br>Ayakkabı 69,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e9.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">64,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Ceket</font></h4>
                                <p>
                                    Pantolon 50,00 TL
                                    <br>Ayakkabı 45,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e6.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">73,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Hırka</font></h4>
                                <p>
                                    Pantolon 65,00 TL
                                    <br>Gömlek 35,99 TL
                                    <br>Ayakkabı 39,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e8.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">95,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Ceket</font></h4>
                                <p>
                                    Pantolon 62,00 TL
                                    <br>Kazak 35,99 TL
                                    <br>Ayakkabı 76,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e3.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">159,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Ceket</font></h4>
                                <p>
                                    Pantolon 80,00 TL
                                    <br>Gömlek 69,99 TL
                                    <br>Ayakkabı 102,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e4.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">173,00 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Ceket</font></h4>
                                <p>
                                    Pantolon 94,00 TL
                                    <br>Ayakkabı 129,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e5.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">86,99 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Kazak</font></h4>
                                <p>
                                    Pantolon 65,00 TL
                                    <br>Ayakkabı 63,90 TL
                                </p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e7.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">189,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Eşofman Takımı</font></h4>
                                <p>Ayakkabı 97,90 TL</p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/images/e2.jpeg" />
                        <div class="caption">
                            <font face="Buxton Sketch">
                                <h4 class="pull-right"><font face="Buxton Sketch">199,90 TL</font></h4>
                                <h4><font face="Buxton Sketch">Erkek Çocuk Takım Elbise</font></h4>
                                <p>Ayakkabı 89,90 TL</p></font>
                        </div>
                        <div class="ratings">
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

b151210067/b151210067/Views/Home/Magazalarımız.cshtml
@{
    ViewBag.Title = "Magazalarımız";
}

<h2>Magazalarımız</h2>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row carousel-holder">
                <div class="col-md-12">
                    <img src="~/Images/magaza.jpeg" />
                </div>
            </div>

        </div>
    </div>
</div>
<br >

<center>
    <table border="1" width="1000" height="150">

        <tr>
            <td><b><font face="Buxton Sketch">Şehir</font></b></td>
            <td><b><font face="Buxton Sketch">Ulaşım Bilgileri</font></b></td>
            <td><b><font face="Buxton Sketch">İletişim Bilgileri</font></b></td>
        </tr>
        <tr>
            <td><font face="Buxton Sketch">İstanbul</font></td>
            <td><font face="Buxton Sketch">Küçük Çekmece Mah. Çardar Sok NO:2 Üsküdar</font></td>
            <td><font face="Buxton Sketch">216-6023322</font></td>
        </tr>
        <tr>
            <td><font face="Buxton Sketch">İzmir</font></td>
            <td><font face="Buxton Sketch">Zorlu Center Levazım Mah. Koru Sok. No:2</font></td>
            <td><font face="Buxton Sketch">232-3539687</font></td>
        </tr>
        <tr>
            <td><font face="Buxton Sketch">Kocaeli</font></td>
            <td><font face="Buxton Sketch">Tatlıkuyu Mah. Güneyyanyol Cad. GEbze Center Avm No:310</font></td>
            <td><font face="Buxton Sketch">262-6429856</font></td>
        </tr>


    </table>
</center>