b151210067/b151210067/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace b151210067.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int CategoryId { get; set; }
        public int Rating { get; set; }
        public virtual Category Category { get; set; }
        public byte[] Image { get; set; }
    }
}

b151210067/b151210067/Controllers/FileController.cs
using b151210067.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class FileController : Controller
    {
        
        public ActionResult Index([Bind(Prefix = "id")]int furnitureId)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var model = context.Products.Find(furnitureId).Image;
            return File(model, "image/jpeg");
        }

        public ActionResult GetAccessoryImage(int AccessoryId)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var model = context.Accessories.Find(AccessoryId).Image;
            return File(model, "image/jpeg");
        }
    }
}

b151210067/b151210067/Controllers/ProductsController.cs
using b151210067.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b151210067.Controllers
{
    public class ProductsController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult Index(string category)
        {
            var model = context.Products.Where(p => p.Category.Name == category);
            ViewBag.Category = category;
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (context != null)
            {
                context.Dispose();
            }
        }
    }
}

b151210067/b151210067/Views/Products/Index.cshtml
@model IEnumerable<b151210067.Models.Product>
@{
    ViewBag.Title = "Kızcocuk";
}


<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row carousel-holder">
                <div class="col-md-12">
                    @if (ViewBag.Category == "FemaleChild")
                    {
                        <img src="~/Images/kizcocuksayfasi.jpeg" />
                    }
                    else
                    {
                        <img src="~/Images/erkekcocuksayfasi.jpeg" />
                    }
                </div>
            </div>
            <br>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="@Url.Action("Index", "File", new { item.Id })" />
                            <div class="caption">
                                <h4 class="pull-right"><font face="Buxton Sketch">@item.Price TL</font></h4>
                                <h4><font face="Buxton Sketch">@item.Name</font></h4>
                            </div>
                            <div class="ratings">
                                <p>
                                    @{
                                        for (int i = 0; i < item.Rating; i++)
                                        {
                                            <span class="glyphicon glyphicon-star"></span>
                                        }
                                        for (int i = 0; i < 5 - item.Rating; i++)
                                        {
                                            <span class="glyphicon glyphicon-star-empty"></span>
                                        }
                                    }
                                </p>
                            </div>
                        </div>
                    </div>
                                        }



            </div>
        </div>
    </div>
</div>